# 1.1 Numpy ndarray 개요
* ndarray 생성 np.array()

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print("list1 : " , list1)
print("list1 type : ", type(list1))

array1 = np.array(list1)
print("array1:",array1)
print("array1 type:", type(array1))

list1 :  [1, 2, 3]
list1 type :  <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray의 형태(shape)와 차원

In [4]:
array1 = np.array([1, 2, 3])
print("array1 type : ", type(array1))
print("array1 array 형태 : ", array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])  # 리스트를 요소로 가지고 있는 리스트 -> 2차원
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
[[1 2 3]]


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


* ndarray 데이터 값 타입

In [6]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


* astype()을 통한 타입 변환

In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


* ndarray에서 axis 기반의 연산함수 수행 <br>
 axis0 : 행축 방향, axis1 : 열축 방향

In [10]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]
